# Generated by Django 5.1 on 2024-09-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BngJobs',
        ),
        migrations.DeleteModel(
            name='PuneJobs',
        ),
    ]
