# Generated by Django 5.1 on 2024-09-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_delete_bngjobs_delete_punejobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydjobs',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='eligibility',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
